### ISSUE TITLE
replace lib the lib uuidv4 by nanoid

### ISSUE THREAD

**Issue by tgmarinho** [Wellers0n/upload#62]
https://github.com/Wellers0n/upload/blob/13cf8d9cbd910e57f7306f798f5e0efc6ae9f409/packages/server/package.json#LL38C9-L38C9

https://www.npmjs.com/package/nanoid

https://blog.bitsrc.io/why-is-nanoid-replacing-uuid-1b5100e62ed2

**Comment by Wellers0n** [comment]
Thanks!

**Comment by Wellers0n** [comment]
fix: https://github.com/Wellers0n/upload/pull/80
